baseurl = "https://herms14.github.io/Clustered-Thoughts/"
languageCode = "en-us"
theme = "PaperMod"
title = "Clustered Thoughts"

# Theme i18n support
DefaultContentLanguage = "en"

# Set hasCJKLanguage to true for CJK languages
hasCJKLanguage = false

# Enable emoji
enableEmoji = true

# Build drafts in dev
buildDrafts = false

[languages]
    [languages.en]
        languageName = "English"
        title = "Clustered Thoughts"
        weight = 1
        [languages.en.params]
            description = "A homelab journey - from trip photos to full-blown infrastructure"

[pagination]
    pagerSize = 10

[permalinks]
    posts = "/posts/:slug/"

[taxonomies]
    category = "categories"
    tag = "tags"
    series = "series"

[outputs]
    home = ["HTML", "RSS", "JSON"]

[minify]
    disableXML = true
    minifyOutput = true
