[[main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1

[[main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 2

[[main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3

[[main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 4

[[main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 5

[[main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 6
