[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
    [main.params]
        icon = "home"

[[main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 2
    [main.params]
        icon = "archives"

[[main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 3
    [main.params]
        icon = "search"

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/herms14"
    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://linkedin.com/in/hermesmiraflor"
    [social.params]
        icon = "brand-linkedin"
