# Theme Parameters
mainSections = ["posts"]
featuredImageField = "image"
rssFullContent = true

[favicon]
    # Leave empty to use default favicon

[footer]
    since = 2025
    customText = ""

[dateFormat]
    published = "Jan 02, 2006"
    lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar]
    emoji = ""
    subtitle = "Homelab Enthusiast | Infrastructure Builder | Tech Explorer"
    [sidebar.avatar]
        enabled = true
        local = false
        src = "https://avatars.githubusercontent.com/u/herms14"

[article]
    math = false
    toc = true
    readingTime = true
    [article.license]
        enabled = false

[comments]
    enabled = false

[widgets]
    homepage = [
        { type = "search" },
        { type = "archives", limit = 5 },
        { type = "categories", limit = 10 },
        { type = "tag-cloud", limit = 10 }
    ]
    page = [
        { type = "toc" }
    ]

[opengraph]
    [opengraph.twitter]
        site = ""
        card = "summary_large_image"

[defaultImage]
    [defaultImage.opengraph]
        enabled = false
        local = false
        src = ""

[colorScheme]
    toggle = true
    default = "auto"

[imageProcessing]
    [imageProcessing.cover]
        enabled = true
    [imageProcessing.content]
        enabled = true
