baseURL = 'https://herms14.github.io/Clustered-Thoughts/'
languageCode = 'en-us'
title = 'Clustered Thoughts'
theme = 'terminal'

[pagination]
pagerSize = 5

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[params]
  # Terminal theme specific settings
  contentTypeName = "posts"
  themeColor = "green"  # Options: orange, blue, red, green, pink
  showMenuItems = 3
  fullWidthTheme = false
  centerTheme = true
  autoCover = true
  showLastUpdated = false

  # Site info
  author = "Hermes Miraflor II"
  description = "A homelab journey - from trip photos to full-blown infrastructure"
  keywords = "homelab,infrastructure,kubernetes,networking,self-hosting,devops"

  # Social
  github = "herms14"
  linkedin = "hermesmiraflor"

[params.twitter]
  creator = ""
  site = ""

  # Footer
  showFooter = true
  showCopyright = true
  showThemeInfo = true

[params.logo]
  logoText = "~/clustered-thoughts"
  logoHomeLink = "/"

[languages]
  [languages.en]
    languageName = "English"
    title = "Clustered Thoughts"
    subtitle = "A homelab journey"
    owner = "Hermes Miraflor II"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "~/clustered-thoughts"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 2
      [[languages.en.menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 3

[module]
  [module.hugoVersion]
    extended = true
    min = "0.90.0"
